config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create]

  resources :organizations, only: [:new, :create]

  devise_scope :user do
    get '/users/new' => 'users/registrations#new', as: :new_users
    post '/users' => 'users/registrations#create'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/:organization_id' => 'organizations#show', as: :organization

  resources :positions, only: [:new, :create, :show] do
    resources :recruitments, only: [:show, :new, :create] do
      resources :recruitment_steps, only: [:show], path: 'steps' do
        member do
          put :approve
          put :reprove
        end
      end
    end
  end

  root to: 'home#index'
end

app/models/recruitment.rb
class Recruitment < ActiveRecord::Base
  belongs_to :candidate
  belongs_to :recruiter, class_name: 'User' # TODO: Remove this
  belongs_to :position, required: true
  has_and_belongs_to_many :participants,
                          class_name: 'User',
                          association_foreign_key: 'participant_id',
                          join_table: 'recruitments_participants'
  has_many :steps, class_name: 'RecruitmentStep'

  after_save do |recruitment|
    recruitment.position.steps_template.each do |step|
      recruitment.steps.create!(
        order: step['order'],
        title: step['title'],
        description: step['description']
      )
    end
  end

  # Public: The current progress based on approved steps.
  #
  # Examples
  #
  #   recruitment.progress
  #   # => 33.33
  #
  # Returns a Decimal.
  def progress
    total_steps_count = self.steps.count

    if total_steps_count.zero?
      0.0
    else
      approved_steps_count = self.steps.where(state: 'approved').count
      (approved_steps_count * 100.0 / total_steps_count).round(2)
    end
  end

  # Public: The current state based on the overall steps states.
  #
  # The expected states are:
  #   * 'waiting'
  #   * 'reproved'
  #   * 'approved'
  #
  # Returns a String.
  def current_state
    if self.steps.where(state: 'reproved').exists?
      'reproved'
    elsif self.steps.pluck(:state).uniq == ['approved']
      'approved'
    else
      'waiting'
    end
  end

  # Public: The next step a candidate will be evaluated in.
  #
  # It's expected to always be the first waiting step, but there will not be
  # next step if the candidate reproves in at least one step.
  #
  # Returns a RecruitmentStep or nothing.
  def next_step
    if !self.steps.where(state: 'reproved').exists?
      self.steps.order(:order).find_by(state: 'waiting')
    end
  end
end

app/controllers/recruitments_controller.rb
class RecruitmentsController < ApplicationController
  def show
    position = current_user.organization.positions.find(params[:position_id])
    @recruitment = position.recruitments.find(params[:id])
  end

  def new
    @position = current_user.organization.positions.find(params[:position_id])
    @candidate = Candidate.new
  end

  def create
    @position = current_user.organization.positions.find(params[:position_id])
    recruitment = @position.recruitments.build
    candidate_params = params.require(:candidate).permit(:name, :email, :github, :twitter, :linkedin, :skype)
    @candidate = recruitment.build_candidate(candidate_params)

    if recruitment.save
      redirect_to @position, notice: 'Recruitment created with success.'
    else
      render 'new'
    end
  end
end

app/views/recruitments/_recruitment.html.erb
<li class="candidate <%= recruitment.current_state %>">
  <%= link_to [@position, recruitment] do %>
    <%= avatar(recruitment.candidate.avatar, size: "96", alt: recruitment.candidate.name, class: "profile-picture ib") %>

    <div class="info">
      <h3 class="ib"><%= recruitment.candidate.name %></h3>

      <div class="participants">
        <% recruitment.participants.each do |participant| %>
          <%= avatar(participant.avatar, size: "32", alt: participant.name) %>
        <% end %>
        <span class="exceed">+8</span>
      </div>

      <div class="progress-bar">
        <span class="progress" style="width: <%= recruitment.progress %>%"></span>
      </div>
    </div>
  <% end -%>
</li>

app/views/recruitments/new.html.erb
<h2>Create a new candidate</h2>

<%= form_for(@candidate, url: position_recruitments_path(@position)) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :github %>
  <%= f.text_field :github %>

  <%= f.label :twitter %>
  <%= f.text_field :twitter %>

  <%= f.label :linkedin %>
  <%= f.text_field :linkedin %>

  <%= f.label :skype %>
  <%= f.text_field :skype %>

  <%= f.submit 'Create', class: "button create" %>
<% end -%>

app/views/recruitments/show.html.erb
<%= render 'positions/position_data', position: Position.new(title: 'Test', description: 'Test Data', created_at: DateTime.current) %>

<section class="candidate <%= @recruitment.current_state %> recruitment">
  <%= avatar(@recruitment.candidate.avatar, size: "96", alt: @recruitment.candidate.name, class: "profile-picture ib") %>

  <div class="info">
    <h3 class="ib"><%= @recruitment.candidate.name %></h3>

    <div class="participants">
      <% @recruitment.participants.each do |participant| %>
        <%= avatar(participant.avatar, size: "32", alt: participant.name) %>
      <% end %>
    </div>

    <div class="progress-bar">
      <span class="progress" style="width: <%= @recruitment.progress %>%"></span>
    </div>
  </div>
</section>

<section class="steps">
  <ol>
    <% @recruitment.steps.order(:order).each do |step| %>
      <%
        step_html_class = [step.state]
        step_html_class << 'next-step' if step == @recruitment.next_step
      %>

      <%= content_tag :li, class: step_html_class do %>
        <%= link_to step.title, position_recruitment_recruitment_step_path(@recruitment.position, @recruitment, step) %>
      <% end %>
    <% end %>
  </ol>
</section>