config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create]

  resources :organizations, only: [:new, :create]

  devise_scope :user do
    get '/users/new' => 'users/registrations#new', as: :new_users
    post '/users' => 'users/registrations#create'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/:organization_id' => 'organizations#show', as: :organization

  resources :positions, only: [:new, :create, :show] do
    resources :recruitments, only: [:show, :new, :create] do
      resources :recruitment_steps, only: [:show], path: 'steps' do
        member do
          put :approve
          put :reprove
        end
      end
    end
  end

  root to: 'home#index'
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  AlreadyHasOwnerError = Class.new(StandardError)

  belongs_to :owner, class_name: 'User'
  has_many :positions

  validates_presence_of :name

  to_param :name

  def set_owner!(owner)
    if self.owner
      raise AlreadyHasOwnerError, 'Organization already has an owner'
    else
      transaction do
        update!(owner: owner)
        owner.update!(organization: self)
      end
    end
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]

  def new
    @organization = Organization.new
  end

  def create
    organization_params = params.require(:organization).permit(:name)
    @organization = Organization.new(organization_params)

    if @organization.save
      session['devise.organization_id'] = @organization.id
      redirect_to new_users_url
    else
      render 'new'
    end
  end

  def show
    @organization = Organization.find(params[:organization_id])

    if current_user.organization != @organization
      raise ActiveRecord::RecordNotFound
    end
  end
end

app/views/organizations/new.html.erb
<h2>Create a new organization</h2>

<%= form_for(@organization) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

  <div>
    <%= f.submit 'Create', class: "button create" %>
  </div>
<% end -%>

app/views/organizations/show.html.erb
<h2><%= @organization.name %></h2>

<% @organization.positions.each do |position| -%>
  <ul>
    <li><%= link_to position.title, position %></li>
  </ul>
<% end -%>
<%= link_to 'Add a new position', new_position_path, class: "button" %>

<!--
<hr>
<h2>Invite people to <%= @organization.name %></h2>
<form action="?">
  <label for="email">E-mail</label>
  <input type="text" id="email">
  <input type="submit" value="Invite" class="button">
</form>
 -->