config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create]

  resources :organizations, only: [:new, :create]

  devise_scope :user do
    get '/users/new' => 'users/registrations#new', as: :new_users
    post '/users' => 'users/registrations#create'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/:organization_id' => 'organizations#show', as: :organization

  resources :positions, only: [:new, :create, :show] do
    resources :recruitments, only: [:show, :new, :create] do
      resources :recruitment_steps, only: [:show], path: 'steps' do
        member do
          put :approve
          put :reprove
        end
      end
    end
  end

  root to: 'home#index'
end

app/models/recruitment_step.rb
class RecruitmentStep < ActiveRecord::Base
  belongs_to :recruitment
  has_many :comments
end

app/controllers/recruitment_steps_controller.rb
class RecruitmentStepsController < ApplicationController
  def show
    @step = Recruitment.find(params[:recruitment_id]).steps.find(params[:id])
  end

  def approve
    recruitment = Recruitment.find(params[:recruitment_id])
    @step = recruitment.steps.find(params[:id])

    if @step.update(state: 'approved')
      redirect_to [recruitment.position, recruitment], notice: 'Candidate approved on this step'
    end
  end

  def reprove
    recruitment = Recruitment.find(params[:recruitment_id])
    @step = recruitment.steps.find(params[:id])

    if @step.update(state: 'reproved')
      redirect_to [recruitment.position, recruitment], notice: 'Candidate reproved on this step'
    end
  end
end

app/views/recruitment_steps/show.html.erb
<section class="candidate <%= @step.recruitment.current_state %> recruitment step">
  <%= avatar(@step.recruitment.candidate.avatar, size: "96", alt: @step.recruitment.candidate.name, class: "profile-picture ib") %>

  <div class="info">
    <h3 class="ib"><%= @step.recruitment.candidate.name %></h3>
    <div class="progress-bar">
      <span class="progress" style="width: <%= @step.recruitment.progress %>%"></span>
    </div>
  </div>
</section>

<section class="actions">
  <%= link_to 'Approve candidate', approve_position_recruitment_recruitment_step_path, class: "button approve", method: :put %>
  <%= link_to 'Reprove candidate', reprove_position_recruitment_recruitment_step_path, class: "button reprove", method: :put %>
</section>


<section class="step-info">
  <h4><span class="step-indicator"><%= @step.order %></span> <%= @step.title %></h4>
  <p><%= @step.description %></p>
</section>

<section class="comments">
  <h5>Comments about the candidate</h5>

  <div class="comments-wrapper">
    <% @step.comments.each do |comment| %>
      <article>
        <div class="meta">
          <%= avatar(comment.author.avatar, size: "48", alt: comment.author.name, class: "profile-picture ib") %>
          <h6 class="name"><%= comment.author.name %></h6>
          <p class="timestamp"><%= l comment.created_at, format: :long %></p>
        </div>

        <div class="comment-content">
          <%= sanitize comment.body %>
        </div>
        <hr>
      </article>
    <% end %>

    <div class="comment-form">
      <div class="meta">
        <%= avatar(current_user.avatar, size: "48", alt: current_user.name, class: "profile-picture ib") %>
        <h6 class="name"><%= current_user.name %></h6>
      </div>

      <div class="elements">
        <%= form_for Comment.new do |f| %>
          <%= hidden_field_tag :recruitment_step_id, @step.id %>

          <label for="commentBox">Write your comment</label>
          <div id="commentBox" class="textarea" contenteditable></div>
          <%= f.text_area :body, class: 'theComment' %>

          <div class="actions">
            <%= f.submit 'Post', class: 'button' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

<script>
  var commentElement = document.querySelector('.textarea'),
    textArea = document.querySelector('#comment_body');

    if(commentElement) {
      commentElement.addEventListener('keyup', function(e) {
      textArea.value = commentElement.innerHTML;
    }, false);
  }
</script>