config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create]

  resources :organizations, only: [:new, :create]

  devise_scope :user do
    get '/users/new' => 'users/registrations#new', as: :new_users
    post '/users' => 'users/registrations#create'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/:organization_id' => 'organizations#show', as: :organization

  resources :positions, only: [:new, :create, :show] do
    resources :recruitments, only: [:show, :new, :create] do
      resources :recruitment_steps, only: [:show], path: 'steps' do
        member do
          put :approve
          put :reprove
        end
      end
    end
  end

  root to: 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mitto</title>
  <meta charset="utf-8">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Abril+Fatface|Open+Sans:400,700,400italic|Montserrat:400,700">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <h1>
      <% if user_signed_in? -%>
        <%= link_to 'Mitto', organization_path(current_user.organization) %>
      <% else -%>
        <a href="/">Mitto</a>
      <% end -%>
    </h1>
    <ul class="navigation">
        <% if user_signed_in? -%>
          <li class="user-info">
            <p class="profile-picture"><%= avatar(current_user.avatar, size: "64", alt: current_user.name) %></p>
            <p class="user-name"><%= current_user.name %></p>
            <p class="logout"><%= link_to raw('&times;'), destroy_user_session_path, method: :delete, title: "Log out" %></p>
          </li>
        <% else -%>
          <li class="session-actions">
            <p><%= link_to 'Sign In', new_user_session_path %></p>
            <p><%= link_to 'Sign Up', new_organization_path %></p>
          </li>
        <% end -%>
      </li>
    </ul>
  </header>

  <section class="messages">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </section>

  <div class="content">
    <%= yield %>
  </div>


<!-- Place this before your </body> tag. -->
<script type="text/javascript">
var rumbleBannerBackgroundColor, rumbleBannerTextColor, rumbleBannerLinkColor, rumbleBannerPlacement;
rumbleBannerBackgroundColor = "rgba(200,200,200,.3)";
rumbleBannerTextColor = "#333";
rumbleBannerLinkColor = "#F30";
rumbleBannerPlacement = "bottom"; // Optionally replace with "bottom".
</script>
<script src="https://d4nnn7wspfa3h.cloudfront.net/banner-2014.js" type="text/javascript"></script>

</body>
</html>